// Code generated by cmd/gen; DO NOT EDIT.

package qbittorrent

// deepCopyTorrent returns a pointer to a Torrent whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyTorrent(t *Torrent) *Torrent {
	if t == nil {
		return nil
	}
	c := *t

	if c.AddedOn != nil {
		v := *c.AddedOn
		c.AddedOn = &v
	}

	if c.AmountLeft != nil {
		v := *c.AmountLeft
		c.AmountLeft = &v
	}

	if c.AutoTMM != nil {
		v := *c.AutoTMM
		c.AutoTMM = &v
	}

	if c.Availability != nil {
		v := *c.Availability
		c.Availability = &v
	}

	if c.Category != nil {
		v := *c.Category
		c.Category = &v
	}

	if c.Completed != nil {
		v := *c.Completed
		c.Completed = &v
	}

	if c.CompletionOn != nil {
		v := *c.CompletionOn
		c.CompletionOn = &v
	}

	if c.ContentPath != nil {
		v := *c.ContentPath
		c.ContentPath = &v
	}

	if c.DlLimit != nil {
		v := *c.DlLimit
		c.DlLimit = &v
	}

	if c.DlSpeed != nil {
		v := *c.DlSpeed
		c.DlSpeed = &v
	}

	if c.Downloaded != nil {
		v := *c.Downloaded
		c.Downloaded = &v
	}

	if c.DownloadedSession != nil {
		v := *c.DownloadedSession
		c.DownloadedSession = &v
	}

	if c.ETA != nil {
		v := *c.ETA
		c.ETA = &v
	}

	if c.FirstLastPiecePrio != nil {
		v := *c.FirstLastPiecePrio
		c.FirstLastPiecePrio = &v
	}

	if c.ForceStart != nil {
		v := *c.ForceStart
		c.ForceStart = &v
	}

	if c.Hash != nil {
		v := *c.Hash
		c.Hash = &v
	}

	if c.InfoHashV1 != nil {
		v := *c.InfoHashV1
		c.InfoHashV1 = &v
	}

	if c.InfoHashV2 != nil {
		v := *c.InfoHashV2
		c.InfoHashV2 = &v
	}

	if c.LastActivity != nil {
		v := *c.LastActivity
		c.LastActivity = &v
	}

	if c.MagnetURI != nil {
		v := *c.MagnetURI
		c.MagnetURI = &v
	}

	if c.MaxRatio != nil {
		v := *c.MaxRatio
		c.MaxRatio = &v
	}

	if c.MaxSeedingTime != nil {
		v := *c.MaxSeedingTime
		c.MaxSeedingTime = &v
	}

	if c.Name != nil {
		v := *c.Name
		c.Name = &v
	}

	if c.NumComplete != nil {
		v := *c.NumComplete
		c.NumComplete = &v
	}

	if c.NumIncomplete != nil {
		v := *c.NumIncomplete
		c.NumIncomplete = &v
	}

	if c.NumLeechs != nil {
		v := *c.NumLeechs
		c.NumLeechs = &v
	}

	if c.NumSeeds != nil {
		v := *c.NumSeeds
		c.NumSeeds = &v
	}

	if c.Priority != nil {
		v := *c.Priority
		c.Priority = &v
	}

	if c.Progress != nil {
		v := *c.Progress
		c.Progress = &v
	}

	if c.Ratio != nil {
		v := *c.Ratio
		c.Ratio = &v
	}

	if c.RatioLimit != nil {
		v := *c.RatioLimit
		c.RatioLimit = &v
	}

	if c.SavePath != nil {
		v := *c.SavePath
		c.SavePath = &v
	}

	if c.DownloadPath != nil {
		v := *c.DownloadPath
		c.DownloadPath = &v
	}

	if c.SeedingTime != nil {
		v := *c.SeedingTime
		c.SeedingTime = &v
	}

	if c.SeedingTimeLimit != nil {
		v := *c.SeedingTimeLimit
		c.SeedingTimeLimit = &v
	}

	if c.SeenComplete != nil {
		v := *c.SeenComplete
		c.SeenComplete = &v
	}

	if c.SequentialDownload != nil {
		v := *c.SequentialDownload
		c.SequentialDownload = &v
	}

	if c.Size != nil {
		v := *c.Size
		c.Size = &v
	}

	if c.State != nil {
		v := *c.State
		c.State = &v
	}

	if c.SuperSeeding != nil {
		v := *c.SuperSeeding
		c.SuperSeeding = &v
	}

	if c.Tags != nil {
		v := *c.Tags
		c.Tags = &v
	}

	if c.TimeActive != nil {
		v := *c.TimeActive
		c.TimeActive = &v
	}

	if c.TotalSize != nil {
		v := *c.TotalSize
		c.TotalSize = &v
	}

	if c.Tracker != nil {
		v := *c.Tracker
		c.Tracker = &v
	}

	if c.TrackersCount != nil {
		v := *c.TrackersCount
		c.TrackersCount = &v
	}

	if c.UpLimit != nil {
		v := *c.UpLimit
		c.UpLimit = &v
	}

	if c.Uploaded != nil {
		v := *c.Uploaded
		c.Uploaded = &v
	}

	if c.UploadedSession != nil {
		v := *c.UploadedSession
		c.UploadedSession = &v
	}

	if c.UpSpeed != nil {
		v := *c.UpSpeed
		c.UpSpeed = &v
	}

	if c.InactiveSeedingTimeLimit != nil {
		v := *c.InactiveSeedingTimeLimit
		c.InactiveSeedingTimeLimit = &v
	}

	if c.Reannounce != nil {
		v := *c.Reannounce
		c.Reannounce = &v
	}

	if c.PopularityScore != nil {
		v := *c.PopularityScore
		c.PopularityScore = &v
	}

	if c.Private != nil {
		v := *c.Private
		c.Private = &v
	}
	return &c
}

// deepCopyTorrentProperties returns a pointer to a TorrentProperties whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyTorrentProperties(t *TorrentProperties) *TorrentProperties {
	if t == nil {
		return nil
	}
	c := *t

	if c.AdditionDate != nil {
		v := *c.AdditionDate
		c.AdditionDate = &v
	}

	if c.Comment != nil {
		v := *c.Comment
		c.Comment = &v
	}

	if c.CompletionDate != nil {
		v := *c.CompletionDate
		c.CompletionDate = &v
	}

	if c.CreatedBy != nil {
		v := *c.CreatedBy
		c.CreatedBy = &v
	}

	if c.CreationDate != nil {
		v := *c.CreationDate
		c.CreationDate = &v
	}

	if c.DlLimit != nil {
		v := *c.DlLimit
		c.DlLimit = &v
	}

	if c.DlSpeed != nil {
		v := *c.DlSpeed
		c.DlSpeed = &v
	}

	if c.DlSpeedAvg != nil {
		v := *c.DlSpeedAvg
		c.DlSpeedAvg = &v
	}

	if c.DownloadPath != nil {
		v := *c.DownloadPath
		c.DownloadPath = &v
	}

	if c.ETA != nil {
		v := *c.ETA
		c.ETA = &v
	}

	if c.Hash != nil {
		v := *c.Hash
		c.Hash = &v
	}

	if c.InfoHashV1 != nil {
		v := *c.InfoHashV1
		c.InfoHashV1 = &v
	}

	if c.InfoHashV2 != nil {
		v := *c.InfoHashV2
		c.InfoHashV2 = &v
	}

	if c.IsPrivate != nil {
		v := *c.IsPrivate
		c.IsPrivate = &v
	}

	if c.LastSeen != nil {
		v := *c.LastSeen
		c.LastSeen = &v
	}

	if c.Name != nil {
		v := *c.Name
		c.Name = &v
	}

	if c.NbConnections != nil {
		v := *c.NbConnections
		c.NbConnections = &v
	}

	if c.NbConnectionsLimit != nil {
		v := *c.NbConnectionsLimit
		c.NbConnectionsLimit = &v
	}

	if c.Peers != nil {
		v := *c.Peers
		c.Peers = &v
	}

	if c.PeersTotal != nil {
		v := *c.PeersTotal
		c.PeersTotal = &v
	}

	if c.PieceSize != nil {
		v := *c.PieceSize
		c.PieceSize = &v
	}

	if c.PiecesHave != nil {
		v := *c.PiecesHave
		c.PiecesHave = &v
	}

	if c.PiecesNum != nil {
		v := *c.PiecesNum
		c.PiecesNum = &v
	}

	if c.Reannounce != nil {
		v := *c.Reannounce
		c.Reannounce = &v
	}

	if c.SavePath != nil {
		v := *c.SavePath
		c.SavePath = &v
	}

	if c.SeedingTime != nil {
		v := *c.SeedingTime
		c.SeedingTime = &v
	}

	if c.Seeds != nil {
		v := *c.Seeds
		c.Seeds = &v
	}

	if c.SeedsTotal != nil {
		v := *c.SeedsTotal
		c.SeedsTotal = &v
	}

	if c.ShareRatio != nil {
		v := *c.ShareRatio
		c.ShareRatio = &v
	}

	if c.TimeElapsed != nil {
		v := *c.TimeElapsed
		c.TimeElapsed = &v
	}

	if c.TotalDownloaded != nil {
		v := *c.TotalDownloaded
		c.TotalDownloaded = &v
	}

	if c.TotalDownloadedSession != nil {
		v := *c.TotalDownloadedSession
		c.TotalDownloadedSession = &v
	}

	if c.TotalSize != nil {
		v := *c.TotalSize
		c.TotalSize = &v
	}

	if c.TotalUploaded != nil {
		v := *c.TotalUploaded
		c.TotalUploaded = &v
	}

	if c.TotalUploadedSession != nil {
		v := *c.TotalUploadedSession
		c.TotalUploadedSession = &v
	}

	if c.TotalWasted != nil {
		v := *c.TotalWasted
		c.TotalWasted = &v
	}

	if c.UpLimit != nil {
		v := *c.UpLimit
		c.UpLimit = &v
	}

	if c.UpSpeed != nil {
		v := *c.UpSpeed
		c.UpSpeed = &v
	}

	if c.UpSpeedAvg != nil {
		v := *c.UpSpeedAvg
		c.UpSpeedAvg = &v
	}
	return &c
}

// deepCopyTorrentFile returns a pointer to a TorrentFile whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyTorrentFile(t *TorrentFile) *TorrentFile {
	if t == nil {
		return nil
	}
	c := *t

	if c.Availability != nil {
		v := *c.Availability
		c.Availability = &v
	}

	if c.Index != nil {
		v := *c.Index
		c.Index = &v
	}

	if c.IsSeed != nil {
		v := *c.IsSeed
		c.IsSeed = &v
	}

	if c.Name != nil {
		v := *c.Name
		c.Name = &v
	}

	if c.Priority != nil {
		v := *c.Priority
		c.Priority = &v
	}

	if c.Progress != nil {
		v := *c.Progress
		c.Progress = &v
	}

	if c.Size != nil {
		v := *c.Size
		c.Size = &v
	}
	return &c
}

// deepCopyTorrentTracker returns a pointer to a TorrentTracker whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyTorrentTracker(t *TorrentTracker) *TorrentTracker {
	if t == nil {
		return nil
	}
	c := *t

	if c.Message != nil {
		v := *c.Message
		c.Message = &v
	}

	if c.NumDownloaded != nil {
		v := *c.NumDownloaded
		c.NumDownloaded = &v
	}

	if c.NumLeeches != nil {
		v := *c.NumLeeches
		c.NumLeeches = &v
	}

	if c.NumPeers != nil {
		v := *c.NumPeers
		c.NumPeers = &v
	}

	if c.NumSeeds != nil {
		v := *c.NumSeeds
		c.NumSeeds = &v
	}

	if c.Status != nil {
		v := *c.Status
		c.Status = &v
	}

	if c.Tier != nil {
		v := *c.Tier
		c.Tier = &v
	}

	if c.URL != nil {
		v := *c.URL
		c.URL = &v
	}
	return &c
}

// deepCopyTransferInfo returns a pointer to a TransferInfo whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyTransferInfo(t *TransferInfo) *TransferInfo {
	if t == nil {
		return nil
	}
	c := *t

	if c.ConnectionStatus != nil {
		v := *c.ConnectionStatus
		c.ConnectionStatus = &v
	}

	if c.DHTNodes != nil {
		v := *c.DHTNodes
		c.DHTNodes = &v
	}

	if c.DlInfoData != nil {
		v := *c.DlInfoData
		c.DlInfoData = &v
	}

	if c.DlInfoSpeed != nil {
		v := *c.DlInfoSpeed
		c.DlInfoSpeed = &v
	}

	if c.DlRateLimit != nil {
		v := *c.DlRateLimit
		c.DlRateLimit = &v
	}

	if c.UpInfoData != nil {
		v := *c.UpInfoData
		c.UpInfoData = &v
	}

	if c.UpInfoSpeed != nil {
		v := *c.UpInfoSpeed
		c.UpInfoSpeed = &v
	}

	if c.UpRateLimit != nil {
		v := *c.UpRateLimit
		c.UpRateLimit = &v
	}

	if c.UseAltSpeedLimits != nil {
		v := *c.UseAltSpeedLimits
		c.UseAltSpeedLimits = &v
	}

	if c.RefreshInterval != nil {
		v := *c.RefreshInterval
		c.RefreshInterval = &v
	}

	if c.WriteCache != nil {
		v := *c.WriteCache
		c.WriteCache = &v
	}

	if c.ReadCache != nil {
		v := *c.ReadCache
		c.ReadCache = &v
	}

	if c.FreeSpace != nil {
		v := *c.FreeSpace
		c.FreeSpace = &v
	}

	if c.GlobalRatio != nil {
		v := *c.GlobalRatio
		c.GlobalRatio = &v
	}

	if c.QueuedIOJobs != nil {
		v := *c.QueuedIOJobs
		c.QueuedIOJobs = &v
	}

	if c.AverageTimeQueue != nil {
		v := *c.AverageTimeQueue
		c.AverageTimeQueue = &v
	}

	if c.TotalBuffersSize != nil {
		v := *c.TotalBuffersSize
		c.TotalBuffersSize = &v
	}

	if c.TotalPeerConnections != nil {
		v := *c.TotalPeerConnections
		c.TotalPeerConnections = &v
	}
	return &c
}

// deepCopyServerState returns a pointer to a ServerState whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyServerState(t *ServerState) *ServerState {
	if t == nil {
		return nil
	}
	c := *t

	if c.AllTimeDownload != nil {
		v := *c.AllTimeDownload
		c.AllTimeDownload = &v
	}

	if c.AllTimeUpload != nil {
		v := *c.AllTimeUpload
		c.AllTimeUpload = &v
	}

	if c.AverageTimeQueue != nil {
		v := *c.AverageTimeQueue
		c.AverageTimeQueue = &v
	}

	if c.ConnectionStatus != nil {
		v := *c.ConnectionStatus
		c.ConnectionStatus = &v
	}

	if c.DHTNodes != nil {
		v := *c.DHTNodes
		c.DHTNodes = &v
	}

	if c.DlInfoData != nil {
		v := *c.DlInfoData
		c.DlInfoData = &v
	}

	if c.DlInfoSpeed != nil {
		v := *c.DlInfoSpeed
		c.DlInfoSpeed = &v
	}

	if c.DlRateLimit != nil {
		v := *c.DlRateLimit
		c.DlRateLimit = &v
	}

	if c.FreeSpaceOnDisk != nil {
		v := *c.FreeSpaceOnDisk
		c.FreeSpaceOnDisk = &v
	}

	if c.GlobalRatio != nil {
		v := *c.GlobalRatio
		c.GlobalRatio = &v
	}

	if c.GlobalSeedingTime != nil {
		v := *c.GlobalSeedingTime
		c.GlobalSeedingTime = &v
	}

	if c.QueuedIOJobs != nil {
		v := *c.QueuedIOJobs
		c.QueuedIOJobs = &v
	}

	if c.Queueing != nil {
		v := *c.Queueing
		c.Queueing = &v
	}

	if c.ReadCacheHits != nil {
		v := *c.ReadCacheHits
		c.ReadCacheHits = &v
	}

	if c.ReadCacheOverload != nil {
		v := *c.ReadCacheOverload
		c.ReadCacheOverload = &v
	}

	if c.RefreshInterval != nil {
		v := *c.RefreshInterval
		c.RefreshInterval = &v
	}

	if c.TotalBuffersSize != nil {
		v := *c.TotalBuffersSize
		c.TotalBuffersSize = &v
	}

	if c.TotalPeerConnections != nil {
		v := *c.TotalPeerConnections
		c.TotalPeerConnections = &v
	}

	if c.TotalQueuedSize != nil {
		v := *c.TotalQueuedSize
		c.TotalQueuedSize = &v
	}

	if c.TotalWastedSession != nil {
		v := *c.TotalWastedSession
		c.TotalWastedSession = &v
	}

	if c.UpInfoData != nil {
		v := *c.UpInfoData
		c.UpInfoData = &v
	}

	if c.UpInfoSpeed != nil {
		v := *c.UpInfoSpeed
		c.UpInfoSpeed = &v
	}

	if c.UpRateLimit != nil {
		v := *c.UpRateLimit
		c.UpRateLimit = &v
	}

	if c.UseAltSpeedLimits != nil {
		v := *c.UseAltSpeedLimits
		c.UseAltSpeedLimits = &v
	}

	if c.WriteCacheOverload != nil {
		v := *c.WriteCacheOverload
		c.WriteCacheOverload = &v
	}
	return &c
}

// deepCopyLogEntry returns a pointer to a LogEntry whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyLogEntry(t *LogEntry) *LogEntry {
	if t == nil {
		return nil
	}
	c := *t

	if c.ID != nil {
		v := *c.ID
		c.ID = &v
	}

	if c.Message != nil {
		v := *c.Message
		c.Message = &v
	}

	if c.Timestamp != nil {
		v := *c.Timestamp
		c.Timestamp = &v
	}

	if c.Type != nil {
		v := *c.Type
		c.Type = &v
	}
	return &c
}

// deepCopyPeerLogEntry returns a pointer to a PeerLogEntry whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyPeerLogEntry(t *PeerLogEntry) *PeerLogEntry {
	if t == nil {
		return nil
	}
	c := *t

	if c.Blocked != nil {
		v := *c.Blocked
		c.Blocked = &v
	}

	if c.ID != nil {
		v := *c.ID
		c.ID = &v
	}

	if c.IP != nil {
		v := *c.IP
		c.IP = &v
	}

	if c.Reason != nil {
		v := *c.Reason
		c.Reason = &v
	}

	if c.Timestamp != nil {
		v := *c.Timestamp
		c.Timestamp = &v
	}
	return &c
}

// deepCopyBuildInfo returns a pointer to a BuildInfo whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyBuildInfo(t *BuildInfo) *BuildInfo {
	if t == nil {
		return nil
	}
	c := *t

	if c.Bitness != nil {
		v := *c.Bitness
		c.Bitness = &v
	}

	if c.Boost != nil {
		v := *c.Boost
		c.Boost = &v
	}

	if c.LibTorrent != nil {
		v := *c.LibTorrent
		c.LibTorrent = &v
	}

	if c.OpenSSL != nil {
		v := *c.OpenSSL
		c.OpenSSL = &v
	}

	if c.Platform != nil {
		v := *c.Platform
		c.Platform = &v
	}

	if c.Qt != nil {
		v := *c.Qt
		c.Qt = &v
	}

	if c.Zlib != nil {
		v := *c.Zlib
		c.Zlib = &v
	}
	return &c
}

// deepCopyTorrentPeer returns a pointer to a TorrentPeer whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyTorrentPeer(t *TorrentPeer) *TorrentPeer {
	if t == nil {
		return nil
	}
	c := *t

	if c.Client != nil {
		v := *c.Client
		c.Client = &v
	}

	if c.Connection != nil {
		v := *c.Connection
		c.Connection = &v
	}

	if c.Country != nil {
		v := *c.Country
		c.Country = &v
	}

	if c.CountryCode != nil {
		v := *c.CountryCode
		c.CountryCode = &v
	}

	if c.DlSpeed != nil {
		v := *c.DlSpeed
		c.DlSpeed = &v
	}

	if c.Downloaded != nil {
		v := *c.Downloaded
		c.Downloaded = &v
	}

	if c.Files != nil {
		v := *c.Files
		c.Files = &v
	}

	if c.Flags != nil {
		v := *c.Flags
		c.Flags = &v
	}

	if c.FlagsDesc != nil {
		v := *c.FlagsDesc
		c.FlagsDesc = &v
	}

	if c.IP != nil {
		v := *c.IP
		c.IP = &v
	}

	if c.PeerIDClient != nil {
		v := *c.PeerIDClient
		c.PeerIDClient = &v
	}

	if c.Port != nil {
		v := *c.Port
		c.Port = &v
	}

	if c.Progress != nil {
		v := *c.Progress
		c.Progress = &v
	}

	if c.Relevance != nil {
		v := *c.Relevance
		c.Relevance = &v
	}

	if c.UpSpeed != nil {
		v := *c.UpSpeed
		c.UpSpeed = &v
	}

	if c.Uploaded != nil {
		v := *c.Uploaded
		c.Uploaded = &v
	}
	return &c
}

// deepCopySearchStatus returns a pointer to a SearchStatus whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopySearchStatus(t *SearchStatus) *SearchStatus {
	if t == nil {
		return nil
	}
	c := *t

	if c.ID != nil {
		v := *c.ID
		c.ID = &v
	}

	if c.Status != nil {
		v := *c.Status
		c.Status = &v
	}

	if c.Total != nil {
		v := *c.Total
		c.Total = &v
	}
	return &c
}

// deepCopySearchResult returns a pointer to a SearchResult whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopySearchResult(t *SearchResult) *SearchResult {
	if t == nil {
		return nil
	}
	c := *t

	if c.DescrLink != nil {
		v := *c.DescrLink
		c.DescrLink = &v
	}

	if c.FileName != nil {
		v := *c.FileName
		c.FileName = &v
	}

	if c.FileSize != nil {
		v := *c.FileSize
		c.FileSize = &v
	}

	if c.FileURL != nil {
		v := *c.FileURL
		c.FileURL = &v
	}

	if c.NbLeechers != nil {
		v := *c.NbLeechers
		c.NbLeechers = &v
	}

	if c.NbSeeders != nil {
		v := *c.NbSeeders
		c.NbSeeders = &v
	}

	if c.SiteURL != nil {
		v := *c.SiteURL
		c.SiteURL = &v
	}
	return &c
}

// deepCopyTorrentCreationStatus returns a pointer to a TorrentCreationStatus whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyTorrentCreationStatus(t *TorrentCreationStatus) *TorrentCreationStatus {
	if t == nil {
		return nil
	}
	c := *t

	if c.ElapsedTime != nil {
		v := *c.ElapsedTime
		c.ElapsedTime = &v
	}

	if c.ID != nil {
		v := *c.ID
		c.ID = &v
	}

	if c.Progress != nil {
		v := *c.Progress
		c.Progress = &v
	}

	if c.Status != nil {
		v := *c.Status
		c.Status = &v
	}
	return &c
}

// deepCopyRSSAutoDownloadRule returns a pointer to a RSSAutoDownloadRule whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyRSSAutoDownloadRule(t *RSSAutoDownloadRule) *RSSAutoDownloadRule {
	if t == nil {
		return nil
	}
	c := *t

	if c.AddPaused != nil {
		v := *c.AddPaused
		c.AddPaused = &v
	}

	if c.TorrentParams != nil {
		v := *c.TorrentParams
		c.TorrentParams = &v
	}
	return &c
}

// deepCopyRSSRuleTorrentParams returns a pointer to a RSSRuleTorrentParams whose pointer fields are
// independently allocated so callers cannot mutate internal state through them.
// Returns nil if t is nil.
// Generated by cmd/gen — edit types.go then re-run go generate.
func deepCopyRSSRuleTorrentParams(t *RSSRuleTorrentParams) *RSSRuleTorrentParams {
	if t == nil {
		return nil
	}
	c := *t

	if c.UseAutoTMM != nil {
		v := *c.UseAutoTMM
		c.UseAutoTMM = &v
	}
	return &c
}
