// Code generated by cmd/gen; DO NOT EDIT.

package qbittorrent

// mergePartialTorrent copies fields from src into dst using presence-aware
// semantics:
//   - pointer fields (*T): copied only when src value is non-nil
//   - plain bool fields: always overwritten (false is a meaningful value)
//   - value fields (int, string, float): copied only when src value is non-zero
//
// Generated by cmd/gen — edit types.go then re-run go generate.
func mergePartialTorrent(dst, src *Torrent) {

	if src.AddedOn != nil {
		dst.AddedOn = src.AddedOn
	}

	if src.AmountLeft != nil {
		dst.AmountLeft = src.AmountLeft
	}

	if src.AutoTMM != nil {
		dst.AutoTMM = src.AutoTMM
	}

	if src.Availability != nil {
		dst.Availability = src.Availability
	}

	if src.Category != nil {
		dst.Category = src.Category
	}

	if src.Completed != nil {
		dst.Completed = src.Completed
	}

	if src.CompletionOn != nil {
		dst.CompletionOn = src.CompletionOn
	}

	if src.ContentPath != nil {
		dst.ContentPath = src.ContentPath
	}

	if src.DlLimit != nil {
		dst.DlLimit = src.DlLimit
	}

	if src.DlSpeed != nil {
		dst.DlSpeed = src.DlSpeed
	}

	if src.Downloaded != nil {
		dst.Downloaded = src.Downloaded
	}

	if src.DownloadedSession != nil {
		dst.DownloadedSession = src.DownloadedSession
	}

	if src.ETA != nil {
		dst.ETA = src.ETA
	}

	if src.FirstLastPiecePrio != nil {
		dst.FirstLastPiecePrio = src.FirstLastPiecePrio
	}

	if src.ForceStart != nil {
		dst.ForceStart = src.ForceStart
	}

	if src.Hash != nil {
		dst.Hash = src.Hash
	}

	if src.InfoHashV1 != nil {
		dst.InfoHashV1 = src.InfoHashV1
	}

	if src.InfoHashV2 != nil {
		dst.InfoHashV2 = src.InfoHashV2
	}

	if src.LastActivity != nil {
		dst.LastActivity = src.LastActivity
	}

	if src.MagnetURI != nil {
		dst.MagnetURI = src.MagnetURI
	}

	if src.MaxRatio != nil {
		dst.MaxRatio = src.MaxRatio
	}

	if src.MaxSeedingTime != nil {
		dst.MaxSeedingTime = src.MaxSeedingTime
	}

	if src.Name != nil {
		dst.Name = src.Name
	}

	if src.NumComplete != nil {
		dst.NumComplete = src.NumComplete
	}

	if src.NumIncomplete != nil {
		dst.NumIncomplete = src.NumIncomplete
	}

	if src.NumLeechs != nil {
		dst.NumLeechs = src.NumLeechs
	}

	if src.NumSeeds != nil {
		dst.NumSeeds = src.NumSeeds
	}

	if src.Priority != nil {
		dst.Priority = src.Priority
	}

	if src.Progress != nil {
		dst.Progress = src.Progress
	}

	if src.Ratio != nil {
		dst.Ratio = src.Ratio
	}

	if src.RatioLimit != nil {
		dst.RatioLimit = src.RatioLimit
	}

	if src.SavePath != nil {
		dst.SavePath = src.SavePath
	}

	if src.DownloadPath != nil {
		dst.DownloadPath = src.DownloadPath
	}

	if src.SeedingTime != nil {
		dst.SeedingTime = src.SeedingTime
	}

	if src.SeedingTimeLimit != nil {
		dst.SeedingTimeLimit = src.SeedingTimeLimit
	}

	if src.SeenComplete != nil {
		dst.SeenComplete = src.SeenComplete
	}

	if src.SequentialDownload != nil {
		dst.SequentialDownload = src.SequentialDownload
	}

	if src.Size != nil {
		dst.Size = src.Size
	}

	if src.State != nil {
		dst.State = src.State
	}

	if src.SuperSeeding != nil {
		dst.SuperSeeding = src.SuperSeeding
	}

	if src.Tags != nil {
		dst.Tags = src.Tags
	}

	if src.TimeActive != nil {
		dst.TimeActive = src.TimeActive
	}

	if src.TotalSize != nil {
		dst.TotalSize = src.TotalSize
	}

	if src.Tracker != nil {
		dst.Tracker = src.Tracker
	}

	if src.TrackersCount != nil {
		dst.TrackersCount = src.TrackersCount
	}

	if src.UpLimit != nil {
		dst.UpLimit = src.UpLimit
	}

	if src.Uploaded != nil {
		dst.Uploaded = src.Uploaded
	}

	if src.UploadedSession != nil {
		dst.UploadedSession = src.UploadedSession
	}

	if src.UpSpeed != nil {
		dst.UpSpeed = src.UpSpeed
	}

	if src.InactiveSeedingTimeLimit != nil {
		dst.InactiveSeedingTimeLimit = src.InactiveSeedingTimeLimit
	}

	if src.Reannounce != nil {
		dst.Reannounce = src.Reannounce
	}

	if src.PopularityScore != nil {
		dst.PopularityScore = src.PopularityScore
	}

	if src.Private != nil {
		dst.Private = src.Private
	}
}

// mergePartialServerState copies fields from src into dst using presence-aware
// semantics:
//   - pointer fields (*T): copied only when src value is non-nil
//   - plain bool fields: always overwritten (false is a meaningful value)
//   - value fields (int, string, float): copied only when src value is non-zero
//
// Generated by cmd/gen — edit types.go then re-run go generate.
func mergePartialServerState(dst, src *ServerState) {

	if src.AllTimeDownload != nil {
		dst.AllTimeDownload = src.AllTimeDownload
	}

	if src.AllTimeUpload != nil {
		dst.AllTimeUpload = src.AllTimeUpload
	}

	if src.AverageTimeQueue != nil {
		dst.AverageTimeQueue = src.AverageTimeQueue
	}

	if src.ConnectionStatus != nil {
		dst.ConnectionStatus = src.ConnectionStatus
	}

	if src.DHTNodes != nil {
		dst.DHTNodes = src.DHTNodes
	}

	if src.DlInfoData != nil {
		dst.DlInfoData = src.DlInfoData
	}

	if src.DlInfoSpeed != nil {
		dst.DlInfoSpeed = src.DlInfoSpeed
	}

	if src.DlRateLimit != nil {
		dst.DlRateLimit = src.DlRateLimit
	}

	if src.FreeSpaceOnDisk != nil {
		dst.FreeSpaceOnDisk = src.FreeSpaceOnDisk
	}

	if src.GlobalRatio != nil {
		dst.GlobalRatio = src.GlobalRatio
	}

	if src.GlobalSeedingTime != nil {
		dst.GlobalSeedingTime = src.GlobalSeedingTime
	}

	if src.QueuedIOJobs != nil {
		dst.QueuedIOJobs = src.QueuedIOJobs
	}

	if src.Queueing != nil {
		dst.Queueing = src.Queueing
	}

	if src.ReadCacheHits != nil {
		dst.ReadCacheHits = src.ReadCacheHits
	}

	if src.ReadCacheOverload != nil {
		dst.ReadCacheOverload = src.ReadCacheOverload
	}

	if src.RefreshInterval != nil {
		dst.RefreshInterval = src.RefreshInterval
	}

	if src.TotalBuffersSize != nil {
		dst.TotalBuffersSize = src.TotalBuffersSize
	}

	if src.TotalPeerConnections != nil {
		dst.TotalPeerConnections = src.TotalPeerConnections
	}

	if src.TotalQueuedSize != nil {
		dst.TotalQueuedSize = src.TotalQueuedSize
	}

	if src.TotalWastedSession != nil {
		dst.TotalWastedSession = src.TotalWastedSession
	}

	if src.UpInfoData != nil {
		dst.UpInfoData = src.UpInfoData
	}

	if src.UpInfoSpeed != nil {
		dst.UpInfoSpeed = src.UpInfoSpeed
	}

	if src.UpRateLimit != nil {
		dst.UpRateLimit = src.UpRateLimit
	}

	if src.UseAltSpeedLimits != nil {
		dst.UseAltSpeedLimits = src.UseAltSpeedLimits
	}

	if src.WriteCacheOverload != nil {
		dst.WriteCacheOverload = src.WriteCacheOverload
	}
}
