// Code generated by cmd/gen; DO NOT EDIT.

package qbittorrent

import "sort"

// TorrentSort defines sort criteria for a torrent slice.
type TorrentSort struct {
	// Field is the torrent field to sort by. Use the JSON field names
	// that the qBittorrent API accepts (e.g. "name", "added_on", "size").
	// An empty or unrecognised field falls back to sorting by "hash".
	Field string

	// Reverse sorts in descending order when true.
	Reverse bool
}

// SortTorrents sorts a torrent slice in-place by the given criteria.
// An empty or unrecognised Field falls back to sorting by hash.
func SortTorrents(torrents []Torrent, opts TorrentSort) {
	s := &torrentSorter{data: torrents, cmp: torrentCmpFunc(opts.Field), less: lessAsc}
	if opts.Reverse {
		s.less = lessDesc
	}
	sort.Sort(s)
}

// torrentSorter implements sort.Interface. Pointer receiver avoids copying
// the struct on every Len/Less/Swap call through the interface.
type torrentSorter struct {
	data []Torrent
	cmp  func(a, b *Torrent) int
	less func(s *torrentSorter, i, j int) bool
}

func (s *torrentSorter) Len() int              { return len(s.data) }
func (s *torrentSorter) Swap(i, j int)         { s.data[i], s.data[j] = s.data[j], s.data[i] }
func (s *torrentSorter) Less(i, j int) bool    { return s.less(s, i, j) }
func lessAsc(s *torrentSorter, i, j int) bool  { return s.cmp(&s.data[i], &s.data[j]) < 0 }
func lessDesc(s *torrentSorter, i, j int) bool { return s.cmp(&s.data[i], &s.data[j]) > 0 }

// torrentCmpFunc returns a comparison function for the given sort field.
// Lookup is O(1) via map. Falls back to hash comparison for unrecognised fields.
func torrentCmpFunc(field string) func(a, b *Torrent) int {
	if fn, ok := torrentSortFields[field]; ok {
		return fn
	}
	return cmpTorrentHash
}

// cmpPtr compares two pointer values using native operators. nil sorts first.
// Single nil guard covers the rare case; hot path (both non-nil) is one branch.
// Equality is checked first because for strings == short-circuits on length
// mismatch (O(1)) before falling through to a single < for direction.
func cmpPtr[T interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~float32 | ~float64 | ~string
}](a, b *T) int {
	if a == nil || b == nil {
		if a == b {
			return 0
		}
		if a == nil {
			return -1
		}
		return 1
	}
	if *a == *b {
		return 0
	}
	if *a < *b {
		return -1
	}
	return 1
}

// cmpPtrBool compares two *bool values. nil < false < true.
// Single nil guard covers the rare case; hot path (both non-nil) is one branch.
func cmpPtrBool(a, b *bool) int {
	if a == nil || b == nil {
		if a == b {
			return 0
		}
		if a == nil {
			return -1
		}
		return 1
	}
	if *a == *b {
		return 0
	}
	if !*a {
		return -1
	}
	return 1
}

// torrentSortFields maps JSON field names to named comparison functions.
// Generated by cmd/gen — edit types.go then re-run go generate.
var torrentSortFields = map[string]func(a, b *Torrent) int{
	"added_on":                    cmpTorrentAddedOn,
	"amount_left":                 cmpTorrentAmountLeft,
	"auto_tmm":                    cmpTorrentAutoTMM,
	"availability":                cmpTorrentAvailability,
	"category":                    cmpTorrentCategory,
	"completed":                   cmpTorrentCompleted,
	"completion_on":               cmpTorrentCompletionOn,
	"content_path":                cmpTorrentContentPath,
	"dl_limit":                    cmpTorrentDlLimit,
	"dlspeed":                     cmpTorrentDlSpeed,
	"downloaded":                  cmpTorrentDownloaded,
	"downloaded_session":          cmpTorrentDownloadedSession,
	"eta":                         cmpTorrentETA,
	"f_l_piece_prio":              cmpTorrentFirstLastPiecePrio,
	"force_start":                 cmpTorrentForceStart,
	"hash":                        cmpTorrentHash,
	"infohash_v1":                 cmpTorrentInfoHashV1,
	"infohash_v2":                 cmpTorrentInfoHashV2,
	"last_activity":               cmpTorrentLastActivity,
	"magnet_uri":                  cmpTorrentMagnetURI,
	"max_ratio":                   cmpTorrentMaxRatio,
	"max_seeding_time":            cmpTorrentMaxSeedingTime,
	"name":                        cmpTorrentName,
	"num_complete":                cmpTorrentNumComplete,
	"num_incomplete":              cmpTorrentNumIncomplete,
	"num_leechs":                  cmpTorrentNumLeechs,
	"num_seeds":                   cmpTorrentNumSeeds,
	"priority":                    cmpTorrentPriority,
	"progress":                    cmpTorrentProgress,
	"ratio":                       cmpTorrentRatio,
	"ratio_limit":                 cmpTorrentRatioLimit,
	"save_path":                   cmpTorrentSavePath,
	"download_path":               cmpTorrentDownloadPath,
	"seeding_time":                cmpTorrentSeedingTime,
	"seeding_time_limit":          cmpTorrentSeedingTimeLimit,
	"seen_complete":               cmpTorrentSeenComplete,
	"seq_dl":                      cmpTorrentSequentialDownload,
	"size":                        cmpTorrentSize,
	"state":                       cmpTorrentState,
	"super_seeding":               cmpTorrentSuperSeeding,
	"tags":                        cmpTorrentTags,
	"time_active":                 cmpTorrentTimeActive,
	"total_size":                  cmpTorrentTotalSize,
	"tracker":                     cmpTorrentTracker,
	"trackers_count":              cmpTorrentTrackersCount,
	"up_limit":                    cmpTorrentUpLimit,
	"uploaded":                    cmpTorrentUploaded,
	"uploaded_session":            cmpTorrentUploadedSession,
	"upspeed":                     cmpTorrentUpSpeed,
	"inactive_seeding_time_limit": cmpTorrentInactiveSeedingTimeLimit,
	"reannounce":                  cmpTorrentReannounce,
	"popularity":                  cmpTorrentPopularityScore,
	"private":                     cmpTorrentPrivate,
}

func cmpTorrentAddedOn(a, b *Torrent) int {
	return cmpPtr(a.AddedOn, b.AddedOn)
}

func cmpTorrentAmountLeft(a, b *Torrent) int {
	return cmpPtr(a.AmountLeft, b.AmountLeft)
}

func cmpTorrentAutoTMM(a, b *Torrent) int {
	return cmpPtrBool(a.AutoTMM, b.AutoTMM)
}

func cmpTorrentAvailability(a, b *Torrent) int {
	return cmpPtr(a.Availability, b.Availability)
}

func cmpTorrentCategory(a, b *Torrent) int {
	return cmpPtr(a.Category, b.Category)
}

func cmpTorrentCompleted(a, b *Torrent) int {
	return cmpPtr(a.Completed, b.Completed)
}

func cmpTorrentCompletionOn(a, b *Torrent) int {
	return cmpPtr(a.CompletionOn, b.CompletionOn)
}

func cmpTorrentContentPath(a, b *Torrent) int {
	return cmpPtr(a.ContentPath, b.ContentPath)
}

func cmpTorrentDlLimit(a, b *Torrent) int {
	return cmpPtr(a.DlLimit, b.DlLimit)
}

func cmpTorrentDlSpeed(a, b *Torrent) int {
	return cmpPtr(a.DlSpeed, b.DlSpeed)
}

func cmpTorrentDownloaded(a, b *Torrent) int {
	return cmpPtr(a.Downloaded, b.Downloaded)
}

func cmpTorrentDownloadedSession(a, b *Torrent) int {
	return cmpPtr(a.DownloadedSession, b.DownloadedSession)
}

func cmpTorrentETA(a, b *Torrent) int {
	return cmpPtr(a.ETA, b.ETA)
}

func cmpTorrentFirstLastPiecePrio(a, b *Torrent) int {
	return cmpPtrBool(a.FirstLastPiecePrio, b.FirstLastPiecePrio)
}

func cmpTorrentForceStart(a, b *Torrent) int {
	return cmpPtrBool(a.ForceStart, b.ForceStart)
}

func cmpTorrentHash(a, b *Torrent) int {
	return cmpPtr(a.Hash, b.Hash)
}

func cmpTorrentInfoHashV1(a, b *Torrent) int {
	return cmpPtr(a.InfoHashV1, b.InfoHashV1)
}

func cmpTorrentInfoHashV2(a, b *Torrent) int {
	return cmpPtr(a.InfoHashV2, b.InfoHashV2)
}

func cmpTorrentLastActivity(a, b *Torrent) int {
	return cmpPtr(a.LastActivity, b.LastActivity)
}

func cmpTorrentMagnetURI(a, b *Torrent) int {
	return cmpPtr(a.MagnetURI, b.MagnetURI)
}

func cmpTorrentMaxRatio(a, b *Torrent) int {
	return cmpPtr(a.MaxRatio, b.MaxRatio)
}

func cmpTorrentMaxSeedingTime(a, b *Torrent) int {
	return cmpPtr(a.MaxSeedingTime, b.MaxSeedingTime)
}

func cmpTorrentName(a, b *Torrent) int {
	return cmpPtr(a.Name, b.Name)
}

func cmpTorrentNumComplete(a, b *Torrent) int {
	return cmpPtr(a.NumComplete, b.NumComplete)
}

func cmpTorrentNumIncomplete(a, b *Torrent) int {
	return cmpPtr(a.NumIncomplete, b.NumIncomplete)
}

func cmpTorrentNumLeechs(a, b *Torrent) int {
	return cmpPtr(a.NumLeechs, b.NumLeechs)
}

func cmpTorrentNumSeeds(a, b *Torrent) int {
	return cmpPtr(a.NumSeeds, b.NumSeeds)
}

func cmpTorrentPriority(a, b *Torrent) int {
	return cmpPtr(a.Priority, b.Priority)
}

func cmpTorrentProgress(a, b *Torrent) int {
	return cmpPtr(a.Progress, b.Progress)
}

func cmpTorrentRatio(a, b *Torrent) int {
	return cmpPtr(a.Ratio, b.Ratio)
}

func cmpTorrentRatioLimit(a, b *Torrent) int {
	return cmpPtr(a.RatioLimit, b.RatioLimit)
}

func cmpTorrentSavePath(a, b *Torrent) int {
	return cmpPtr(a.SavePath, b.SavePath)
}

func cmpTorrentDownloadPath(a, b *Torrent) int {
	return cmpPtr(a.DownloadPath, b.DownloadPath)
}

func cmpTorrentSeedingTime(a, b *Torrent) int {
	return cmpPtr(a.SeedingTime, b.SeedingTime)
}

func cmpTorrentSeedingTimeLimit(a, b *Torrent) int {
	return cmpPtr(a.SeedingTimeLimit, b.SeedingTimeLimit)
}

func cmpTorrentSeenComplete(a, b *Torrent) int {
	return cmpPtr(a.SeenComplete, b.SeenComplete)
}

func cmpTorrentSequentialDownload(a, b *Torrent) int {
	return cmpPtrBool(a.SequentialDownload, b.SequentialDownload)
}

func cmpTorrentSize(a, b *Torrent) int {
	return cmpPtr(a.Size, b.Size)
}

func cmpTorrentState(a, b *Torrent) int {
	return cmpPtr(a.State, b.State)
}

func cmpTorrentSuperSeeding(a, b *Torrent) int {
	return cmpPtrBool(a.SuperSeeding, b.SuperSeeding)
}

func cmpTorrentTags(a, b *Torrent) int {
	return cmpPtr(a.Tags, b.Tags)
}

func cmpTorrentTimeActive(a, b *Torrent) int {
	return cmpPtr(a.TimeActive, b.TimeActive)
}

func cmpTorrentTotalSize(a, b *Torrent) int {
	return cmpPtr(a.TotalSize, b.TotalSize)
}

func cmpTorrentTracker(a, b *Torrent) int {
	return cmpPtr(a.Tracker, b.Tracker)
}

func cmpTorrentTrackersCount(a, b *Torrent) int {
	return cmpPtr(a.TrackersCount, b.TrackersCount)
}

func cmpTorrentUpLimit(a, b *Torrent) int {
	return cmpPtr(a.UpLimit, b.UpLimit)
}

func cmpTorrentUploaded(a, b *Torrent) int {
	return cmpPtr(a.Uploaded, b.Uploaded)
}

func cmpTorrentUploadedSession(a, b *Torrent) int {
	return cmpPtr(a.UploadedSession, b.UploadedSession)
}

func cmpTorrentUpSpeed(a, b *Torrent) int {
	return cmpPtr(a.UpSpeed, b.UpSpeed)
}

func cmpTorrentInactiveSeedingTimeLimit(a, b *Torrent) int {
	return cmpPtr(a.InactiveSeedingTimeLimit, b.InactiveSeedingTimeLimit)
}

func cmpTorrentReannounce(a, b *Torrent) int {
	return cmpPtr(a.Reannounce, b.Reannounce)
}

func cmpTorrentPopularityScore(a, b *Torrent) int {
	return cmpPtr(a.PopularityScore, b.PopularityScore)
}

func cmpTorrentPrivate(a, b *Torrent) int {
	return cmpPtrBool(a.Private, b.Private)
}
